apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: kong-jwt
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  # header_names: [Authorization]
  claims_to_verify: [exp]
  secret_is_base64: false
  run_on_preflight: true
plugin: jwt